name: CD - Deploy

on:
  workflow_run:
    workflows: ["CI - Build and Push to Main"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Download backend artifact from previous CI workflow
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend
          path: ./publish

      # 3. Download frontend artifact from previous CI workflow
      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend
          path: ./client/dist

      # 4. Install flyctl
      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      # 5. Deploy to Fly.io
      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          fly deploy --config fly.toml --remote-only
